---
- name: Create MongoDB data directory
  file:
    path: "/data/db"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  tags: [mongodb, directories]

- name: Pull MongoDB Docker image
  docker_image:
    name: "{{ mongodb_image }}"
    source: pull
  tags: [mongodb, docker]

- name: Create MongoDB volume
  docker_volume:
    name: "{{ mongodb_volume }}"
    driver: local
  tags: [mongodb, docker, volumes]
